title: Trimming Circles
author: Leo
email: leo@extensity.ai
github_username: futurisold
x_username: futurisold
goodreads_username: 90047214-claudiu-leoveanu-condrei

url: "https://futurisold.github.io"
baseurl: "/trimming-circles"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: katex

footer_only_homepage: true
footer_text: "68747470733A2F2F796F7574752E62652F68317A38394A43347149773F743D3630"

profile-picture: assets/profile.png
favicon_location: assets/favicon.png

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css
    quiet_deps: true


navbar:
 - name: "About"
   link: "about"

exclude:
  - Gemfile
  - Gemfile.lock
